"""UI components package."""

from app.ui.components.widget_names import (
    # Constants
    WINDOW_NAME,
    REGION_SIDEBAR, REGION_CONTENT, REGION_STATUS_BAR,
    REGION_SYSTEM_MONITOR, REGION_COMMAND_PALETTE, REGION_SHORTCUTS_HELP,
    SIDEBAR_NAV, SIDEBAR_FOOTER,
    HUB_PRIMARY, HUB_WORKSPACE, HUB_MORE, HUB_SETTINGS,
    # Page names
    PAGE_HOME, PAGE_HELP, PAGE_CHAT, PAGE_TEAM, PAGE_MODELS,
    PAGE_MONITOR, PAGE_CHATS, PAGE_TRACK, PAGE_WORK,
    PAGE_APPROVALS, PAGE_PATCHES, PAGE_KNOWLEDGE, PAGE_SCHEDULE,
    PAGE_ORG_CHART, PAGE_MEMORY, PAGE_PROJECTS, PAGE_COMPANY,
    PAGE_CEO, PAGE_AGENTS, PAGE_TASKS, PAGE_RUNS, PAGE_USAGE,
    PAGE_SETTINGS, PAGE_ABOUT,
    # Chat regions
    CHAT_MESSAGES, CHAT_COMPOSER, CHAT_SIDEBAR, CHAT_TOOLBAR, CHAT_STATUS,
    # Prefixes
    PREFIX_BUTTON, PREFIX_LABEL, PREFIX_FRAME, PREFIX_SCROLL,
    PREFIX_TEXTBOX, PREFIX_ENTRY, PREFIX_PANEL, PREFIX_HEADER,
    PREFIX_FOOTER, PREFIX_BAR, PREFIX_MENU, PREFIX_TAB,
    PREFIX_CANVAS, PREFIX_IMAGE, PREFIX_SEPARATOR, PREFIX_DIALOG,
    PREFIX_POPUP, PREFIX_SPLITTER, PREFIX_GROUP,
    # Functions
    build_name, set_widget_name, get_widget_name,
    find_widget_by_name, find_widgets_by_prefix,
    name_sidebar_nav_button, name_sidebar_hub_header, name_sidebar_hub_items_frame,
    name_sidebar_footer_button, name_page_root, name_page_header,
    name_page_body, name_page_save_bar,
    name_chat_messages_scroll, name_chat_message_bubble,
    name_chat_composer_input, name_chat_composer_send_btn,
    name_chat_composer_attach_btn, name_chat_composer_mic_btn, name_chat_composer_speak_btn,
    name_chat_composer_mode_chip, name_chat_toolbar_button,
    name_chat_toolbar_provider_menu, name_chat_toolbar_model_menu,
    name_chat_toolbar_model_search,
    name_chat_sidebar_panel, name_page_sidebar, name_chat_sidebar_button,
    name_chat_topbar_title, name_chat_topbar_mode_chip,
    name_chat_topbar_tasks_chip, name_chat_topbar_risk_chip,
    name_chat_topbar_caps_chip, name_chat_sidebar_search,
    name_status_bar_label, name_system_monitor_metric, name_dialog, name_component,
    # Creator functions
    create_named_button, create_named_label, create_named_frame,
    create_named_scrollable_frame, create_named_textbox,
    create_named_entry, create_named_toplevel,
    # Registry
    WidgetRegistry, widget_registry, register_widget,
)

__all__ = [
    "WINDOW_NAME",
    "REGION_SIDEBAR", "REGION_CONTENT", "REGION_STATUS_BAR",
    "REGION_SYSTEM_MONITOR", "REGION_COMMAND_PALETTE", "REGION_SHORTCUTS_HELP",
    "SIDEBAR_NAV", "SIDEBAR_FOOTER",
    "HUB_PRIMARY", "HUB_WORKSPACE", "HUB_MORE", "HUB_SETTINGS",
    "PAGE_HOME", "PAGE_HELP", "PAGE_CHAT", "PAGE_TEAM", "PAGE_MODELS",
    "PAGE_MONITOR", "PAGE_CHATS", "PAGE_TRACK", "PAGE_WORK",
    "PAGE_APPROVALS", "PAGE_PATCHES", "PAGE_KNOWLEDGE", "PAGE_SCHEDULE",
    "PAGE_ORG_CHART", "PAGE_MEMORY", "PAGE_PROJECTS", "PAGE_COMPANY",
    "PAGE_CEO", "PAGE_AGENTS", "PAGE_TASKS", "PAGE_RUNS", "PAGE_USAGE",
    "PAGE_SETTINGS", "PAGE_ABOUT",
    "CHAT_MESSAGES", "CHAT_COMPOSER", "CHAT_SIDEBAR", "CHAT_TOOLBAR", "CHAT_STATUS",
    "PREFIX_BUTTON", "PREFIX_LABEL", "PREFIX_FRAME", "PREFIX_SCROLL",
    "PREFIX_TEXTBOX", "PREFIX_ENTRY", "PREFIX_PANEL", "PREFIX_HEADER",
    "PREFIX_FOOTER", "PREFIX_BAR", "PREFIX_MENU", "PREFIX_TAB",
    "PREFIX_CANVAS", "PREFIX_IMAGE", "PREFIX_SEPARATOR", "PREFIX_DIALOG",
    "PREFIX_POPUP", "PREFIX_SPLITTER", "PREFIX_GROUP",
    "build_name", "set_widget_name", "get_widget_name",
    "find_widget_by_name", "find_widgets_by_prefix",
    "name_sidebar_nav_button", "name_sidebar_hub_header", "name_sidebar_hub_items_frame",
    "name_sidebar_footer_button", "name_page_root", "name_page_header",
    "name_page_body", "name_page_save_bar",
    "name_chat_messages_scroll", "name_chat_message_bubble",
    "name_chat_composer_input", "name_chat_composer_send_btn",
    "name_chat_composer_attach_btn", "name_chat_composer_mic_btn", "name_chat_composer_speak_btn",
    "name_chat_composer_mode_chip", "name_chat_toolbar_button",
    "name_chat_toolbar_provider_menu", "name_chat_toolbar_model_menu",
    "name_chat_toolbar_model_search",
    "name_chat_sidebar_panel", "name_page_sidebar", "name_chat_sidebar_button",
    "name_chat_topbar_title", "name_chat_topbar_mode_chip",
    "name_chat_topbar_tasks_chip", "name_chat_topbar_risk_chip",
    "name_chat_topbar_caps_chip", "name_chat_sidebar_search",
    "name_status_bar_label", "name_system_monitor_metric", "name_dialog", "name_component",
    "create_named_button", "create_named_label", "create_named_frame",
    "create_named_scrollable_frame", "create_named_textbox",
    "create_named_entry", "create_named_toplevel",
    "WidgetRegistry", "widget_registry", "register_widget",
]
