#!/usr/bin/env python3
"""Generate optional branding pack under assets/branding/ (Pillow).

Original indigo rounded-square "A" mark — no third-party logos.
Also builds a multi-size Windows .ico for PyInstaller.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "branding"

# Indigo matching UI brand_bar / tray fallback
FILL = (99, 102, 241, 255)  # #6366f1
WHITE = (255, 255, 255, 255)


def _draw_mark(size: int):
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    pad = max(1, size // 32)
    radius = max(4, size // 5)
    draw.rounded_rectangle(
        (pad, pad, size - pad - 1, size - pad - 1),
        radius=radius,
        fill=FILL,
    )
    # Stylized "A" — scale from 64px reference
    s = size / 64.0
    poly = [
        (32 * s, 14 * s),
        (18 * s, 50 * s),
        (24 * s, 50 * s),
        (28 * s, 38 * s),
        (36 * s, 38 * s),
        (40 * s, 50 * s),
        (46 * s, 50 * s),
    ]
    draw.polygon([(int(x), int(y)) for x, y in poly], fill=WHITE)
    # Crossbar cutout in brand color
    draw.rectangle(
        (int(27 * s), int(30 * s), int(37 * s), int(34 * s)),
        fill=FILL,
    )
    return img


def _svg_logo() -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="AI Agent Studio">
  <title>AI Agent Studio</title>
  <rect x="2" y="2" width="60" height="60" rx="14" fill="#6366f1"/>
  <polygon points="32,14 18,50 24,50 28,38 36,38 40,50 46,50" fill="#ffffff"/>
  <rect x="27" y="30" width="10" height="4" fill="#6366f1"/>
</svg>
"""


def generate(out: Path | None = None, *, force: bool = False) -> Path:
    from PIL import Image

    dest = Path(out) if out else OUT
    dest.mkdir(parents=True, exist_ok=True)

    sizes = (256, 64, 32, 16)
    images: dict[int, Image.Image] = {}
    for size in sizes:
        images[size] = _draw_mark(size)
        png = dest / f"app_icon_{size}.png"
        if force or not png.is_file():
            images[size].save(png, format="PNG")
            print(f"wrote {png}")
        else:
            print(f"keep  {png}")

    tray = dest / "tray_icon.png"
    if force or not tray.is_file():
        images[64].save(tray, format="PNG")
        print(f"wrote {tray}")
    else:
        print(f"keep  {tray}")

    svg = dest / "logo.svg"
    if force or not svg.is_file():
        svg.write_text(_svg_logo(), encoding="utf-8")
        print(f"wrote {svg}")
    else:
        print(f"keep  {svg}")

    # Multi-size ICO for Windows / PyInstaller
    ico = dest / "app_icon.ico"
    if force or not ico.is_file():
        # Pillow ICO: pass largest with sizes= list
        ico_sizes = [(256, 256), (64, 64), (32, 32), (16, 16)]
        base = images[256]
        base.save(
            ico,
            format="ICO",
            sizes=ico_sizes,
        )
        print(f"wrote {ico}")
    else:
        print(f"keep  {ico}")

    readme = dest / "README.md"
    if force or not readme.is_file():
        readme.write_text(
            "# Branding pack (optional)\n\n"
            "Replace these files with your own icons. See `docs/BRANDING.md`.\n"
            "Generated by `scripts/generate_branding_assets.py` (original mark).\n",
            encoding="utf-8",
        )
        print(f"wrote {readme}")

    # Also refresh legacy assets/tray_icon.png when branding tray exists
    legacy = ROOT / "assets" / "tray_icon.png"
    try:
        images[64].save(legacy, format="PNG")
        print(f"wrote {legacy} (legacy tray)")
    except Exception as e:  # noqa: BLE001
        print(f"skip legacy tray: {e}")

    return dest


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate assets/branding pack")
    p.add_argument("--out", type=Path, default=None, help="Output directory")
    p.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = p.parse_args(argv)
    try:
        generate(args.out, force=args.force)
    except ImportError:
        print("Pillow required: pip install Pillow", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
